from datetime import date, datetime
from typing import Protocol

from .models import Location, Order, User


class OrderRepo(Protocol):
    def get_one(self, id: int) -> Order | None: ...

    def get(
        self,
        date: date | None = None,
        courier: User | None = None,
    ) -> list[Order]: ...

    def add(self, order: Order) -> Order: ...

    def update(self, order: Order) -> Order: ...

    def delete(self, id: int) -> None: ...

    def delete_older_than(self, cutoff: datetime) -> int: ...


class UserRepo(Protocol):
    def add(self, user: User) -> User: ...

    def get_by_login(self, login: str) -> User | None: ...

    def get(self, id: int) -> User | None: ...

    def get_all(self) -> list[User]: ...


class LocationRepo(Protocol):
    def get(self, id: int) -> Location | None: ...

    def get_by_name(self, name: str) -> Location | None: ...

    def get_all(self) -> list[Location]: ...

    def add(self, location: Location) -> Location: ...

    def update(self, location: Location) -> Location: ...

    def delete(self, id: int) -> None: ...


class UnitOfWork(Protocol):
    def commit(self) -> None: ...

    def rollback(self) -> None: ...


class PasswordHasher(Protocol):
    def hash(self, password: str) -> str: ...

    def verify(self, password: str, password_hash: str | None) -> bool: ...
