"""add rates model

Revision ID: 3911236c851c
Revises: 4308e758bc34
Create Date: 2022-08-17 11:21:05.281077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3911236c851c'
down_revision = '4308e758bc34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('g', sa.Integer(), nullable=True),
    sa.Column('ng', sa.Integer(), nullable=True),
    sa.Column('v', sa.Integer(), nullable=True),
    sa.Column('n', sa.Integer(), nullable=True),
    sa.Column('t', sa.Integer(), nullable=True),
    sa.Column('l', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rates')
    # ### end Alembic commands ###
