"""замена поля role на поле is_admin

Revision ID: c3cf94b2d0b5
Revises: 9c747009dfb1
Create Date: 2025-08-24 23:28:27.383958

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3cf94b2d0b5'
down_revision = '9c747009dfb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=False))
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('ADMIN', 'COURIER', name='user_role'), autoincrement=False, nullable=False))
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
